apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# commonLabels:
#   app.xgeeks.org/team: idp_geekathon
#   backstage.io/kubernetes-id: teah-viriathus-viseu

namespace: idpkathon-dev
# namespace: teah-viriathus-viseu-idp_geekathon-dev

resources:
- ../../base
- ingress.yaml

  # ATENTION name = image.name NOT name = spec.containers[0].name
images:
- name: ghcr.io/xgeeks-geekathon/teah-viriathus-viseu
  newTag: 290140a
- name: ghcr.io/xgeeks-geekathon/teah-viriathus-viseu-datafeeder
  newTag: 290140a
